USE Hotel;
INSERT INTO Client(Surname,Name, Middlename, Gender) VALUES('Kostenko','Maksim','Vasilevich','Male');
INSERT INTO Client(Surname,Name, Middlename, Gender) VALUES('Antonov','Aleksandr','Sergeevich','Male');
INSERT INTO Client(Surname,Name, Middlename, Gender) VALUES('Grinchenko','Kirill','Vitalievich','Male');
INSERT INTO Client(Surname,Name, Middlename, Gender ) VALUES('Baranenko','Aleksandr','Olegovich','Male');
INSERT INTO Client(Surname,Name, Middlename, Gender) VALUES('Shevchenko','Roman','Vladislavovich','Male');
INSERT INTO Client(Surname,Name, Middlename, Gender) VALUES('Prokopenko','Valery','Vladlenovich','Male');
INSERT INTO Client(Surname,Name, Middlename, Gender) VALUES('Romashko','Bogdan','Sergeevich','Male');
INSERT INTO Client(Surname,Name, Middlename, Gender) VALUES('Nesterenko','Oleg','Kirilovich','Male');
INSERT INTO Client(Surname,Name, Middlename, Gender) VALUES('Mironenko','Yana','Anatolievna','Male');
INSERT INTO Client(Surname,Name, Middlename, Gender) VALUES('Aleksandrova','Svitlana','Vladimirovna','Male');
